modLoader="javafml"
loaderVersion="[43,)"
license="AGNYA License"

[[mods]]
modId="sortilege"
version="1.5.3"
displayName="Sortilege"
logoFile="logo.png"
credits=""
authors="Lyof"
description='''Simple magic staffs, enchanting and brewing tweaks, and more!'''

[[dependencies.sortilege]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sortilege]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"